### ISSUE TITLE
Difference between main and rug pulls

### ISSUE THREAD

**Issue by mr-rooftop** [VVlovsky/Smart-Price-Changes-Agent#2]
Hey!
Is there anything that the main branch has that the rug pulls branch hasn't?
Can I just use the rug pulls branch, because it's the newer code, or is there any good reason to use the main branch?

**Comment by venglov** [comment]
Hey @mr-rooftop 
rug pulls is not tested as well as main branch, but generally yes, rug pulls has newer code and in the future part of this code will be merged to main.
